services:
  - docker

env:
  global:
  - DOCKER_HUB_REPO=turbineanalytics/
  - MODULE=docker-spark-cassandra

before_install:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - ./build-and-push-docker-image.sh

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.

  email: false
