services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - export DOCKER_HUB_REPO=turbineanalytics/
  - export MODULE=docker-spark-cassandra

script:
  - ./build-and-push-docker-image.sh

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.

  email: false
